// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-KqeV5zW2FkLTkTO9RgCrLId62hGY-g0',
    appId: '1:231869960195:web:05aa070eacf40b5c213e36',
    messagingSenderId: '231869960195',
    projectId: 'sil-app-c5b47',
    authDomain: 'sil-app-c5b47.firebaseapp.com',
    databaseURL: 'https://sil-app-c5b47-default-rtdb.firebaseio.com',
    storageBucket: 'sil-app-c5b47.appspot.com',
    measurementId: 'G-9N840Z5XS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZMKfa3MjO5DdU9Sd2XILYdwpzdEoHU5o',
    appId: '1:231869960195:android:0fb0f4913d76040d213e36',
    messagingSenderId: '231869960195',
    projectId: 'sil-app-c5b47',
    databaseURL: 'https://sil-app-c5b47-default-rtdb.firebaseio.com',
    storageBucket: 'sil-app-c5b47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ohmwvWHtaNx36KGkVz1_0xsxnEiKxcI',
    appId: '1:231869960195:ios:38533cdfd9c2af19213e36',
    messagingSenderId: '231869960195',
    projectId: 'sil-app-c5b47',
    databaseURL: 'https://sil-app-c5b47-default-rtdb.firebaseio.com',
    storageBucket: 'sil-app-c5b47.appspot.com',
    iosClientId: '231869960195-578ihnp7eqch3d23dc8gtfvu26kfqu59.apps.googleusercontent.com',
    iosBundleId: 'com.example.tilsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ohmwvWHtaNx36KGkVz1_0xsxnEiKxcI',
    appId: '1:231869960195:ios:184c5f22c6edf9a4213e36',
    messagingSenderId: '231869960195',
    projectId: 'sil-app-c5b47',
    databaseURL: 'https://sil-app-c5b47-default-rtdb.firebaseio.com',
    storageBucket: 'sil-app-c5b47.appspot.com',
    iosClientId: '231869960195-a6kuf6hhkrl7s09226i39iu18akva6og.apps.googleusercontent.com',
    iosBundleId: 'com.fluency.tilsApp',
  );
}
