// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYYG1T_t8ym4GkhsJTsrlmyQOEsVlcZHk',
    appId: '1:777208983885:web:0cccba32e76da016e30704',
    messagingSenderId: '777208983885',
    projectId: 'fluency-001',
    authDomain: 'fluency-001.firebaseapp.com',
    storageBucket: 'fluency-001.appspot.com',
    measurementId: 'G-B66FV334PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFSQBn_jBpSaFC1Ll5TGpwh_NTFR_Tnv4',
    appId: '1:777208983885:android:ca67e92d51007761e30704',
    messagingSenderId: '777208983885',
    projectId: 'fluency-001',
    storageBucket: 'fluency-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQHCMp-zjaXENthPQD0VDT2upe4V83jp0',
    appId: '1:777208983885:ios:368d507be4609f6ce30704',
    messagingSenderId: '777208983885',
    projectId: 'fluency-001',
    storageBucket: 'fluency-001.appspot.com',
    iosClientId: '777208983885-2mbuhnm17ino83nfoe5mqdg14cfnhndl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tilsApp',
  );
}
